on: push

jobs:
  linux_x64_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ACT (test)
        run: |
          cat act.sh                          \
          | bash -s -- test                   \
          -e "https://api.ileap.sine.dev"     \
          -u ${{secrets.ACT_USER}}            \
          -p ${{secrets.ACT_PASSWORD}}
  mac_amd64_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ACT (test)
        run: |
          cat act.sh                          \
          | bash -s -- test                   \
          -e "https://api.ileap.sine.dev"     \
          -u ${{secrets.ACT_USER}}            \
          -p ${{secrets.ACT_PASSWORD}}
